import { Metadata } from "next";

const title = "Create Next App";
const description = "Generated by create next app";

export const sharedMetadata: Metadata = {
  metadataBase: new URL(`${process.env.SITE_URL ?? "http://localhost:3000"}`),
  title: {
    default: `${title}`,
    template: `%s | ${title}`,
  },
  openGraph: {
    type: "website",
    title: `${title}`,
    description: `${description}`,
    siteName: `${title}`,
    images: [
      {
        url: `/icons/richlink.jpg`,
      },
    ],
  },
  icons: [
    { rel: "favicon", url: "/icons/favicon.ico" },
    { rel: "icon", url: "/icons/favicon-32x32.png" },
    { rel: "apple-touch-icon", url: "/icons/apple-touch-icon.png" },
  ],
  twitter: {
    card: "summary_large_image",
    site: `${title}`,
    creator: "Salman",
    images: `/icons/richlink.jpg`,
  },
  description: `${description}`,
  authors: [{ name: "Salman", url: "https://github.com/caamaann" }],
};
